:project:
  :build_root: Build/ceedling/
  :release_build: TRUE

:paths:
  :test:
    - test/**     # directory where the unit testing are
  :source:
    - autosar/**      # directory where the functions to test areº1
  :include:
    - autosar/**